distance_sensor:
  adapter_type: "simulated"
  min_distance: 3
  max_distance: 420
  poll_interval: 60
  precision: 0.3
  filter_type: "none"
  sensor_type: "SRF05"

line_sensor:
  distance_between_sensors: 0.180
  sensor_amount: 5
  adapter_type: "simulated"
  cone_radius: 0.1
  cone_height: 0.2
  ui_debug: true

steering:
  real_middle: 0
  real_maximum: 420
  real_minimum: -67
  adapter_type: "simulated"

driving:
  real_maximum: 10
  real_minimum: -10
  real_stopped: 67
  adapter_type: "simulated"
