distance_sensor:
  adapter_type: "simulated"
  min_distance: 3
  max_distance: 820
  poll_interval: 60
  precision: 0.3
  filter_type: "none"
  sensor_type: "SRF05"

line_sensor:
  distance_between_sensors: 0.180
  sensor_amount: 5
  adapter_type: "simulated"
  cone_radius: 0.1
  cone_height: 1
  ui_debug: true

steering:
  adapter_type: "simulated"

driving:
  adapter_type: "simulated"
  maximum_speed: 1
  motor_force: 0.08
  motor_count: 2
  motor_usable_torque_ratio: 0.5
  vehicle_weight: 0.5
  wheel_friction: 0.5
  wheel_radius: 6.5
  maximum_acceleration: 0.08
